data_paths:
  - "./data/eng.csv"
  - "./data/companies.csv"
  - "./data/contacts.csv"
test_data_paths: null
debug_mode: true
debug_mode_sample_size: 2000
cv_num_folds: 2
scoring: "roc_auc"
num_trials: 1
objective_optim_direction: "maximize"
test_size: 0.1
n_estimators_range:
  - 1
  - 2
min_category_freq_range:
  - 1
  - 200
shuffle_data: true
stratify_split: true
fill_dict: null
seed: 1337
