data_paths:
  - "C:/Users/darkr/PycharmProjects/rightbound/data/eng.csv"
  - "C:/Users/darkr/PycharmProjects/rightbound/data/companies.csv"
  - "C:/Users/darkr/PycharmProjects/rightbound/data/contacts.csv"
test_data_paths: null
debug_mode: false
debug_mode_sample_size: 700
cv_num_folds: 5
scoring: "roc_auc"
num_trials: 100
objective_optim_direction: "maximize"
test_size: 0.3
n_estimators_range:
  - 1
  - 100
max_depth_range:
  - 1
  - 6
min_category_freq_range:
  - 1
  - 200
shuffle_data: true
stratify_split: true
